#!/bin/bash -e

# roughly based on this guide: https://kb.ettus.com/Building_and_Installing_the_USRP_Open-Source_Toolchain_(UHD_and_GNU_Radio)_on_Linux

# get OS to the most updated state
apt -y upgrade; apt -y update; apt -y autoremove

# a bunch of dependencies
DEBIAN_FRONTEND=noninteractive apt install -y build-essential cmake doxygen g++ git libboost-all-dev libgmp3-dev libgmp-dev liblog4cpp5-dev liborc-0.4-dev libusb-dev libfftw3-dev libsdl1.2-dev libgsl-dev libqwt-qt5-dev libqt5opengl5-dev python-is-python3 python3-numpy python3-mako python3-sphinx python3-lxml  python3-pyqt5 libzmq3-dev python3-yaml python3-click python3-click-plugins python3-zmq python3-scipy python3-pip python3-gi-cairo swig texinfo vim yasm libusb-1.0-0-dev libncurses5-dev dpdk dpdk-dev libpango-1.0-0 libgtk-3-dev libcanberra-gtk-module texlive-full

# our workspace
pushd /opt

# dpdk
# git clone https://github.com/DPDK/dpdk.git
# pushd dpkd

# uhd build from source, this is the driver that connects to the Ettus Research hardware
git clone https://github.com/EttusResearch/uhd
pushd uhd
git checkout v4.0.0.0
pushd host; mkdir -p build; pushd build
cmake ../; make; make test; make install
ldconfig
export LD_LIBRARY_PATH=/usr/local/lib
popd; popd; popd

uhd_images_downloader

# mpir; MPIR is a fork of the GNU Multi Precision library
git clone https://github.com/wbhart/mpir.git
pushd mpir
./autogen.sh
./configure
make; make check
make install
popd

# gnuradio; the reason for all of this
git clone https://github.com/gnuradio/gnuradio.git
pushd gnuradio
git checkout v3.8.2.0
git submodule update --init --recursive
mkdir build; pushd build
cmake ../
make -j$(nproc) # (number of cores in machine)
# make test
make install
ldconfig
popd; popd
